config/routes.rb
Rails.application.routes.draw do
  resources :ainimals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
root "ainimals#index"
end

app/models/ainimal.rb
class Ainimal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/ainimals_controller.rb
class AinimalsController < ApplicationController
  before_action :set_ainimal, only: %i[ show edit update destroy ]

  # GET /ainimals or /ainimals.json
  def index
    @ainimals = Ainimal.all
  end

  # GET /ainimals/1 or /ainimals/1.json
  def show
  end

  # GET /ainimals/new
  def new
    @ainimal = Ainimal.new
  end

  # GET /ainimals/1/edit
  def edit
  end

  # POST /ainimals or /ainimals.json
  def create
    @ainimal = Ainimal.new(ainimal_params)

    respond_to do |format|
      if @ainimal.save
        format.html { redirect_to ainimal_url(@ainimal), notice: "Ainimal was successfully created." }
        format.json { render :show, status: :created, location: @ainimal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ainimal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ainimals/1 or /ainimals/1.json
  def update
    respond_to do |format|
      if @ainimal.update(ainimal_params)
        format.html { redirect_to ainimal_url(@ainimal), notice: "Ainimal was successfully updated." }
        format.json { render :show, status: :ok, location: @ainimal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ainimal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ainimals/1 or /ainimals/1.json
  def destroy
    @ainimal.destroy

    respond_to do |format|
      format.html { redirect_to ainimals_url, notice: "Ainimal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ainimal
      @ainimal = Ainimal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ainimal_params
      params.require(:ainimal).permit(:name, :animaltype, :image, :desc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ainimals_helper.rb
module AinimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ainimals/_ainimal.html.erb
<div class="card container-fluid" style="--bs-card-border-width: 0px;" id="<%= dom_id ainimal %>">
  <div class="row p-4 justify-content-center">
    <div class="col-3">
      <img style="max-width: 100%; max-height: 100%;" src="<%= ainimal.image %>">
    </div>

    <div class="col-3">
      <div class="row align-items-end">
        <div class="col-7">
          <p style="font-family: 'Montserrat', sans-serif; font-weight:400; font-size: 28px;">
            <%= ainimal.name %>
          </p>
        </div>
        <div class="col">
          <p style="font-family: 'Montserrat', sans-serif; font-weight:400; font-size: 16px;">
            <%= ainimal.animaltype %>
          </p>
        </div>
      </div>

      <p style="font-family: 'Montserrat', sans-serif; font-weight:400; font-size: 14px;">
        <%= ainimal.desc %>
      </p>

      <p>
        <%= link_to "Show this ainimal", ainimal, class:'btn btn-light' %>
      </p>
    </div>
  </div>

</div>
<div class="row justify-content-end">
  <div class="col-5">
    <%= image_tag 'barcode.png' %>
  </div>

</div>

app/views/ainimals/_form.html.erb
<%= form_with(model: ainimal) do |form| %>
  <% if ainimal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ainimal.errors.count, "error") %> prohibited this ainimal from being saved:</h2>

      <ul>
        <% ainimal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for(ainimal) do |f| %>
    <div class="container col-5">
      <%= f.label :name, style: "display: block" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="container col-5">
      <%= f.label :animaltype, style: "display: block" %>
      <%= f.text_field :animaltype, class: 'form-control' %>
    </div>

    <div class="container col-5">
      <%= f.label :image, style: "display: block" %>
      <%= f.text_area :image, class: 'form-control' %>
    </div>

    <div class="container col-5">
      <%= f.label :desc, style: "display: block" %>
      <%= f.text_area :desc, class: 'form-control' %>
    </div>

    <div class="container col-5 mt-3 text-center">
      <%= f.submit class: 'btn btn-dark'%>
    </div>
  <% end %>
<% end %>

app/views/ainimals/_header.html.erb
<nav class="navbar bg-body-tertiary container-fluid bg-white" style="border-bottom: 1px solid black; position: fixed; z-index: 4;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag 'logo.png', style: 'width: 133px; height: 33px;', class: 'd-inline-block align-text-top'%>
    </a>
      <%= link_to "Create new AInimal", new_ainimal_path, class: 'btn btn-dark' %>
  </div>
</nav>

app/views/ainimals/edit.html.erb
<h1>Editing ainimal</h1>

<%= render "form", ainimal: @ainimal %>

<br>

<div class="container col-5 mt-3 text-center">
  <%= link_to "Show this ainimal", @ainimal, class:'btn btn-light' %> |
  <%= link_to "Back to ainimals", ainimals_path, class:'btn btn-light'%>
</div>

app/views/ainimals/index.html.erb
<%= render 'header' %>


<div class="container-fluid row" style="padding-top: 300px; margin-bottom: 60px;">
  <div class="col-1"></div>
  <div class="col-7" >
    <h1 style="font-family: 'Montserrat', sans-serif; font-weight:600; font-size: 36px; letter-spacing: 0.09em; color: black;">Bienvenue chez Ainimals !</h1>
    <h4 style="font-family: 'Montserrat', sans-serif; font-weight:300; font-size: 24px; color: black;">Ce site est un catalogue d’animaux fictif. Nous utilisons l’intelligence artificielle Midjourney pour donner vie à notre imagination et vous transporter dans un monde parallèle où ces bêtes existent. </h4>
  </div>
  <div class="col-4"></div>
</div>
<%# <div class="container-fluid" style="width: 100%; height: 500px; overflow: hidden; position: absolute; z-index: 1;">
  <%= image_tag 'Desktop-min.png', class: 'container-fluid', style: 'max-width: 100%; height: 650px; position: absolute; z-index: 1'%>
<%# </div> %> 
<%# <div class="container-fluid" style="width: 100%; height: 500px; overflow: hidden; position: relative; z-index: 2;  background: linear-gradient(180deg, rgba(0, 0, 0, 0.46) 0%, rgba(0, 0, 0, 0.4232) 0.01%, rgba(0, 0, 0, 0.506) 38.15%, rgba(0, 0, 0, 0.92) 100%);">
  <%= image_tag 'Desktop-min.png', class: 'container-fluid', style: 'max-width: 100%; height: 650px; position: absolute; z-index: 1' %>
<%# </div> %> 


<div class="container flux">

  <div class="container">
    <% @ainimals.each do |ainimal| %>
    <div style="margin-bottom: 50px; margin-top: 50px;">
      <%= render ainimal %>
    </div>
    <% end %>
  </div>

</div>

app/views/ainimals/new.html.erb
<h1 class="text-center">New ainimal</h1>

<%= render "form", ainimal: @ainimal %>

<br>

<div class="text-center">
  <%= link_to "Back to ainimals", ainimals_path, class: 'btn btn-light container text-center col-3' %>
</div>

app/views/ainimals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ainimal %>

<div class="container col-5 mt-3 text-center">
  <%= link_to "Edit this ainimal", edit_ainimal_path(@ainimal), class:'btn btn-light' %> |
  <%= link_to "Back to ainimals", ainimals_path, class:'btn btn-light' %>

  <%= button_to "Destroy this ainimal", @ainimal, method: :delete, class:'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ainimals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>